---
deployment:
  tasks:
    - export DEPLOYPATH=/home/bisharod/bisharod-live

    # Install & build frontend
    - cd $DEPLOYPATH/frontend && npm install && npm run build

    # Clean old files
    - rm -rf /home/bisharod/public_html/*

    # Copy new build to live website
    - /bin/cp -r $DEPLOYPATH/frontend/build/* /home/bisharod/public_html/